service: amazon-fba-image-optimizer

provider:
  name: aws
  runtime: python3.9
  region: us-east-1
  timeout: 300
  memorySize: 2048
  environment:
    AWS_S3_BUCKET: ${env:AWS_S3_BUCKET}
    AWS_ACCESS_KEY_ID: ${env:AWS_ACCESS_KEY_ID}
    AWS_SECRET_ACCESS_KEY: ${env:AWS_SECRET_ACCESS_KEY}
    AWS_REGION: ${env:AWS_REGION}

functions:
  api:
    handler: main.handler
    events:
      - http:
          path: /{proxy+}
          method: ANY
          cors: true

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: true
    slim: true
    strip: false

package:
  exclude:
    - node_modules/**
    - .git/**
    - .vscode/**
    - __pycache__/**
    - .pytest_cache/**
    - tests/**